FROM python:3.11-slim

WORKDIR /app

COPY . .
RUN apt-get update && apt-get install -y wget
RUN wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
RUN apt install -y ./google-chrome-stable_current_amd64.deb
RUN pip install --no-cache-dir -r requirements.txt

CMD ["python", "main.py"]
# CMD ["sleep","infnity"]
